---
title: "rpart"
output: html_document
---
```{r}
load("finalDataFrame-1.rda")
```

```{r}
final$res2004 = final$BushVote2004<final$KerryVote2004
final$res2008 = final$ObamaVote2008>final$MccainVote2008
final$res2012 = final$ObamaVote2012>final$RomneyVote2012
final$res2016 = final$ClintonVote2016>final$TrumpVote2016
final = final[,c(-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-42,-43,-44,-45)]

```


```{r}
nTotal = nrow(final)
chooseTest = sample(nTotal, size = 404, replace = FALSE)
finalTest = final[chooseTest, ]
finalTrain = final[ -chooseTest, ]
```

```{r}
set.seed(12344321)
permuteIndices = sample(2700)
v = 3
folds = matrix(permuteIndices,ncol = 3)
```

```{r}
cps = c(seq(0.0001, 0.001, by = 0.0001), 
       seq(0.001, 0.01, by = 0.001),
       seq(0.01, 0.1, by = 0.01))

preds = matrix(nrow = 2700, ncol = length(cps))
library(rpart)
library(class)
for (i in 1:v) {
  trainFold = as.integer(folds[, -i])
  testFold = folds[, i]
  
  for (j in 1:length(cps)) {
    tree = rpart(res2016 ~ .,
            data = finalTrain[trainFold,],
            method = "class",
            control = rpart.control(cp = cps[j]))
    #preds[testFold,j] = knn(finalTrain[trainFold,],finalTest[testFold,],res2016 ~ .,3,prob = TRUE)
    preds[testFold,j] =
      predict(tree,
              newdata = finalTrain[testFold,-34],
              type = "class")
  }
}
```

```{r}
cvRates = apply(preds, 2, function(oneSet) {
  oneSet[which(oneSet == 1)] = "FALSE"
  oneSet[which(oneSet == 2)] = "TRUE"
  sum(finalTrain$res2016 == oneSet)/2700
})
```

```{r}
which.max(cvRates)
library(ggplot2)
cvRes = data.frame(cps, cvRates)
ggplot(data = cvRes, aes(x = cps, y = cvRates)) +
  geom_line() + 
  labs(x = "Complexity Parameter", y = "Classification Rate")
```

```{r}
cpChoice = cvRes[which.max(cvRates)+2,1]

finalTree = rpart(res2016 ~ .,
                  data = finalTrain,
                  method = "class",
                  control = rpart.control(cp = cpChoice))

#finalTree = knn(finalTrain,finalTest,res2016,3,prob = TRUE)   
testPreds = predict(finalTree, 
              newdata = finalTest[,-34],
              type = "class")

classRate = sum(testPreds == finalTest$res2016) / 
  nrow(finalTest)

classRate
```

```{r}
library(rpart.plot)
prp(finalTree, extra = 2)
```



