---
title: "KNN"
author: "Jieni Wan"
date: "2016"
output: html_document
---
```{r}
load("finalDataFrame.rda")
```

```{r}
final$change0812 = (final$ObamaVote2008 > final$MccainVote2008) != (final$ObamaVote2012 > final$RomneyVote2012)

final$change1216 = (final$ObamaVote2012 > final$RomneyVote2012) != (final$ClintonVote2016 > final$TrumpVote2016)
```

```{r}
nTotal = nrow(final)

set.seed(1234)
TrainIndex = sample(nTotal, 2700, replace = FALSE)

Train = final[TrainIndex, c("percentWhite", "maleHouseholder", "femaleHouseholder", "laborForce", "unemployed", "constructionIndustry", "change0812")]

Test = final[-TrainIndex, c("percentWhite", "maleHouseholder", "femaleHouseholder", "laborForce", "unemployed", "constructionIndustry", "change0812")]

TrainTruth = final[TrainIndex, "change1216"]
```

```{r}
k = 1:20
preds = matrix(nrow = nrow(Test), ncol = length(k))
library(class)
for (j in 1:length(k))  preds[, j] = knn(Train, Test, TrainTruth, j)
```

```{r}
cvRates = apply(preds, 2, function(oneSet) {
  oneSet[oneSet == 1] = TRUE
  oneSet[oneSet == 2] = FALSE
  sum(oneSet) / nrow(preds)
})
```

```{r}
which.max(cvRates)
library(ggplot2)
cvRes = data.frame(k, cvRates)
ggplot(data = cvRes, aes(x = k, y = cvRates)) +
  geom_line() + 
  labs(x = "k value", y = "Classification Rate")
```

```{r}
kChoice = cvRes[which.max(cvRates), 1]
knn = knn(Train, Test, TrainTruth, kChoice)   

```
